### ISSUE TITLE
It's not possible to test abstract class without default constructor

### ISSUE THREAD

**Issue by KrystianDziedziola** [sta-szek/pojo-tester#157]
So, I've got this abstract class which don't have a default constructor.
When I try to test for example **equals** method, invoking the following code:
```
assertPojoMethodsFor(AbstractClass.class).testing(Method.EQUALS).areWellImplemented();
```
is causing an error. It says that it's unable to create object for this class:
```
pl.pojo.tester.internal.instantiator.ObjectInstantiationException: Unable to create object for class: class pl.model.AbstractClass
```

**Comment by sta-szek** [comment]
`ProxyInstantiator` should have possibility to create abstract classes with user defined constructors.
