### ISSUE TITLE
Timestamp break Equals

### ISSUE THREAD

**Issue by hajlaoui-nader** [sta-szek/pojo-tester#221]
Testing a pojo with a Timestamp value, break the equals method and then the assertion return false.
Here's a minimal example :
```
public class MyPOJO {
       private Timestamp timestamp;
}
    @Test
    public void pojosTest() {
        assertPojoMethodsForAll(MyPOJO.class).areWellImplemented();
    }
```

**Comment by sta-szek** [comment]
I cannot reproduce this on 0.7.5 and 0.7.6 versions.

You are missing equas, hashcode, tostring getters and setters on `MyPOJO`.

I made tests on class:

```
@Data
public class MyPOJO {
    private java.sql.Timestamp timestamp1;
//    private java.security.Timestamp timestamp2;
}
```

and the tests are passing.

Can you tell me which version of pojo-tester do you use?
Which Timestamp object do you use? java.sql is working as expected but java.security one is failing.

**Comment by hajlaoui-nader** [comment]
@sta-szek thank you for your comment, i'll provide a full example asap. you can discard this issue.

**Comment by hajlaoui-nader** [comment]
@sta-szek i'm sorry for bothering, i found out that the bug is not related to pojo-tester, something's wrong with lombok and java.sql.timestamp !

Thank you for your time
