### ISSUE TITLE
Project Abandoned?

### ISSUE THREAD

**Issue by ekoutanov** [sta-szek/pojo-tester#234]
Appears that this project is not in active maintenance. There are pull reviews open since 2017. If this is the case, may I suggest flagging it in the README.

In the interim, this fork [https://github.com/obsidiandynamics/pojo-tester](https://github.com/obsidiandynamics/pojo-tester) has been uplifted to support JDK 13.

**Comment by sta-szek** [comment]
Hi, unfortunately I don't have time for this project, however if you are willing to contribute then I can make you a contributor.

Actually would be nice if sb could continue that project.

**Comment by frecco75** [comment]
Hello @sta-szek, I have worked too on this project and PR are coming.
Can you make me a contributor too ?

Thanks

**Comment by sta-szek** [comment]
ok, i will do both of  you guys, just please keep code clean and running.
unfortunately my jenkins instance is down as well, so no CI for that project anymore :/
and the second issue is about releasing i think, but for that i will try to find time and do manually in the worst case. 

thanks for support!

**Comment by ekoutanov** [comment]
Sounds good.

**Comment by sta-szek** [comment]
Thanks!
